### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod-gke-guide#1]
- [x] Fix missing details in the readme.md file.
- [x] Someone from the team needs to follow the guide.
- [x] Fix any issue.
